declare const classNames: {
  readonly account__amount: "account__amount";
  readonly transaction: "transaction";
  readonly pagination__button: "pagination__button";
  readonly pagination__ellipsis: "pagination__ellipsis";
  readonly "user-page": "user-page";
  readonly user__title: "user__title";
  readonly "user__edit-button": "user__edit-button";
  readonly user__error: "user__error";
  readonly account: "account";
  readonly "account--selected": "account--selected";
  readonly account__title: "account__title";
  readonly account__description: "account__description";
  readonly account__content: "account__content";
  readonly account__button: "account__button";
  readonly pagination__nav: "pagination__nav";
  readonly pagination__controls: "pagination__controls";
  readonly pagination__arrow: "pagination__arrow";
  readonly "pagination__arrow--prev": "pagination__arrow--prev";
  readonly "pagination__arrow--next": "pagination__arrow--next";
  readonly pagination__numbers: "pagination__numbers";
  readonly "pagination__button--current": "pagination__button--current";
};
export = classNames;
